app:
  events:
#    type: kafka # или 'internal'
    type: internal # или 'kafka'

spring:
  webflux:
    problemdetails:
      enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    cloud:
      stream:
        kafka:
          binder:
            brokers: localhost:9092
            auto-create-topics: true          # dev only, отключи на prod
            configuration:
              security.protocol: PLAINTEXT
#              security.protocol: SASL_SSL
#                sasl.mechanism: PLAIN
#                sasl.jaas.config: >
#                  org.apache.kafka.common.security.plain.PlainLoginModule required
#                  username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";

          bindings:
            price-events-out-0:
              producer:
                configuration:
                  acks: all
                  enable.idempotence: true
                  max.in.flight.requests.per.connection: 1
                  delivery.timeout.ms: 120000
                  request.timeout.ms: 10000
                  retry.backoff.ms: 200
                  linger.ms: 5
                  batch.size: 65536
                  buffer.memory: 67108864
                  compression.type: lz4

        bindings:
          # StreamBridge producers
          price-events-out-0:
            destination: price-events
            content-type: application/json
            producer:
              partition-count: 3
              partition-key-expression: headers['kafka_messageKey']

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml # Путь к вашему главному файлу
    enabled: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    # Указываем путь к вашему существующему файлу
    url: /v3/api-docs
  api-docs:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      binanceClient:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  retry:
    instances:
      binanceClient:
        maxAttempts: 3
        waitDuration: 500ms
        retryExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - java.io.IOException

#  circuitbreaker:
#    configs:
#      # Общий шаблон для всех внешних API
#      default:
#        slidingWindowSize: 10
#        minimumNumberOfCalls: 5
#        failureRateThreshold: 50
#        waitDurationInOpenState: 10s
#        registerHealthIndicator: true
#    instances:
#      # Конкретные экземпляры просто наследуют шаблон
#      binanceClient:
#        baseConfig: default
#        # Можно переопределить любой параметр точечно
#        waitDurationInOpenState: 20s

#  retry:
#    configs:
#      default:
#        maxAttempts: 3
#        waitDuration: 500ms
#    instances:
#      binanceClient:
#        baseConfig: default


binance:
  api:
    url: "https://api.binance.com"
