services:
  postgres:
    image: postgres:16-alpine
    container_name: crypto-alert-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: crypto_alert
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
