build:
  maxIssues: 0
  weights:
    complexity: 2
    LongParameterList: 1
    style: 1
    comments: 1

complexity:
  active: true
  LongMethod:
    threshold: 60
  # Исправлено: threshold разделен на два параметра
  LongParameterList:
    functionThreshold: 6
    constructorThreshold: 6
  # Исправлено: CyclomaticComplexity заменено на ComplexMethod
#  ComplexMethod:
#    threshold: 15
#  ReturnCount:
#    active: true
#    amount: 3  # Увеличиваем допустимое количество return до 3
#    excludeLabeled: false
#    excludeReturnFromLambda: true
#    excludeGuardClauses: false

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: true
  SuspendFunWithFlowReturnType:
    active: true

naming:
  active: true
  FunctionNaming:
    functionPattern: '[a-z][a-zA-Z0-9]*'
    excludeClassPattern: '$^'
  # Разрешаем бэктики в тестах
#  FunctionNaming:
#    ignoreAnnotated: ['Test']

style:
  active: true
  MaxLineLength:
    maxLineLength: 120
    excludePackageStatements: true
    excludeImportStatements: true
  MagicNumber:
    active: true
    ignoreNumbers: ['-1', '0', '1', '2']
  UnusedPrivateMember:
    active: true
  ForbiddenComment:
    active: false

potential-bugs:
  active: true
  UnsafeCallOnNullableType:
    active: true # Запрещает !!

performance:
  active: true
  SpreadOperator:
    active: false

